# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/caesar.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os
os.environ["QT_QPA_PLATFORM_PLUGIN_PATH"] = "../platforms"

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(601, 480)
        self.lbPlainText = QtWidgets.QLabel(Dialog)
        self.lbPlainText.setGeometry(QtCore.QRect(40, 130, 61, 31))
        self.lbPlainText.setObjectName("lbPlainText")
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setGeometry(QtCore.QRect(120, 130, 441, 87))
        self.textEdit.setObjectName("textEdit")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(110, 420, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(380, 420, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.lbPlainText_2 = QtWidgets.QLabel(Dialog)
        self.lbPlainText_2.setGeometry(QtCore.QRect(170, 40, 251, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.lbPlainText_2.setFont(font)
        self.lbPlainText_2.setObjectName("lbPlainText_2")
        self.textEdit_2 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_2.setGeometry(QtCore.QRect(120, 240, 441, 31))
        self.textEdit_2.setObjectName("textEdit_2")
        self.lbPlainText_3 = QtWidgets.QLabel(Dialog)
        self.lbPlainText_3.setGeometry(QtCore.QRect(40, 240, 61, 31))
        self.lbPlainText_3.setObjectName("lbPlainText_3")
        self.lbPlainText_4 = QtWidgets.QLabel(Dialog)
        self.lbPlainText_4.setGeometry(QtCore.QRect(40, 280, 61, 31))
        self.lbPlainText_4.setObjectName("lbPlainText_4")
        self.textEdit_3 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_3.setGeometry(QtCore.QRect(120, 280, 441, 91))
        self.textEdit_3.setObjectName("textEdit_3")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lbPlainText.setText(_translate("Dialog", "Plain Text"))
        self.pushButton.setText(_translate("Dialog", "Encrypt"))
        self.pushButton_2.setText(_translate("Dialog", "Decrypt"))
        self.lbPlainText_2.setText(_translate("Dialog", "caesar cipher"))
        self.lbPlainText_3.setText(_translate("Dialog", "Plain Text"))
        self.lbPlainText_4.setText(_translate("Dialog", "Plain Text"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
